shopify_enterprise:
  outputs:
    dev:
      account: YZDPKFX-MT94920
      database: SHOPIFY_ECOMMERCE
      password: Training123456$
      role: ACCOUNTADMIN
      schema: shopify_target
      threads: 2
      type: snowflake
      user: jul2026learn
      warehouse: SMALL_WH
  target: dev